"""empty message

Revision ID: 3123bcf44488
Revises: 79ebb7b79bcb
Create Date: 2021-03-23 05:42:58.788029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3123bcf44488'
down_revision = '79ebb7b79bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('bathroom', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('bedroom', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('desc', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('photoname', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('price', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('propertytype', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'propertytype')
    op.drop_column('properties', 'price')
    op.drop_column('properties', 'photoname')
    op.drop_column('properties', 'location')
    op.drop_column('properties', 'desc')
    op.drop_column('properties', 'bedroom')
    op.drop_column('properties', 'bathroom')
    # ### end Alembic commands ###
